[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eafig"
version = "1.2.3"
description = "Manage your hyperparameters more easily."
authors = [{ name = "MugeTong", email = "here5320@gmail.com" }]
license = {"file" = "LICENSE"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
    "OmegaConf",
]

[dependency-groups]
dev = [
    "ruff",
    "pytest"
]

[project.urls]
Homepage = "https://github.com/MugeTong/eafig"
Issues = "https://github.com/MugeTong/eafig/issues"
