from pathlib import Path
from typing import IO, Any, Callable, TypeVar, overload

T = TypeVar("T")

config: dict[str, Any] = ...  # This will be dynamically populated with the current configuration

def from_cli() -> dict: ...
def load(path: str | Path | IO[Any], keep_cli: bool = False) -> dict: ...
def save(path: str | Path | IO[Any], sort_keys: bool = True) -> None: ...
def set(key: str, value: Any) -> None: ...
def get(key: str, default: Any = None) -> Any: ...
@overload
def rootconfig(
    cls: type[T],
    /,
) -> type[T]: ...
@overload
def rootconfig(
    cls: None = None, /, *, frozen: bool = False, strict: bool = True
) -> Callable[[type[T]], type[T]]: ...
def configclass(
    *, name: str, frozen: bool = False, hidden: bool = False, strict: bool = True
) -> Callable[[type[T]], type[T]]: ...
